### ISSUE TITLE
check_internal_links_with_anchors crashes on multilinguial website

### ISSUE THREAD

**Issue by kuon** [Keats/gutenberg#1694]
```
Checking all internal links with anchors.
thread 'main' panicked at 'Couldn't find section in check_internal_links_with_anchors', components/site/src/link_checking.rs:66:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The error happens here

https://github.com/getzola/zola/blob/1ed1fdbee7e580375367e5df00f57af86f116842/components/site/src/link_checking.rs#L65

I think this is caused by ` if md_path.contains("_index.md") {` in my case, the file is named `_index.de.md` as it is in german.

If I change the `contains` call for `if md_path.contains("_index.") {` the issue seems to be fixed but I am not fully sure this is the correct fix.

**Comment by southerntofu** [comment]
So #1780 was merged with the fix. Thanks for the report and the suggested fix! And thanks for merging so quickly! Leaving this note here in case someone wonders why pages containing `_index.` are now unsupported.

I initially wanted to check if the path contained `/_index.` but that would not match the homepage (`_index.` without slash) so i went with your suggestion and documented this behavior. If we'd like to get more clever about this in the future, we could take the filename (last item in the split by '/') and check if it starts with `_index.` so that pages called `foobar_index.md` would be supported as previously. I don't think it's much of a problem personally, but i'm leaving it here in the comment so someone facing this issue linked in the docs understands why it's like this and how we could work around it if really needed.

@Keats i forgot to update the changelog in the PR, could you take care of it maybe? however small it is i believe this new limitation in page names should be documented as a "breaking change" which will likely affect nobody but still
