### ISSUE TITLE
"content/index.md" results in two identical pages

### ISSUE THREAD

**Issue by Elinvynia** [Keats/gutenberg#2082]
# Bug Report

## Environment

Zola version: 0.16.1

## Expected Behavior
$base_url/content/ should not exist

## Current Behavior
$base_url/content/ is created and is a duplicate of $base_url/

## Step to reproduce
Create a file named index.md in folder named content, give it a template, generate the site and watch the page be duplicated.
(both public/index.html and public/content/index.html exist)

**Comment by Keats** [comment]
It should be fixed in the `next` branch! It will now be an error to have a file named `index.md` in a section folder, it will be reserved for colocated assets directories.

I _think_ I might end up allowing it before the next version release but I'm 100% sure, I might have been focused on removing the error vs thinking on how it would work.

**Comment by Elinvynia** [comment]
Thanks a lot, at first I was confused since I didn't have any `content/_index.md` but after renaming `content/index.md` to `content/_index.md` the issue was resolved!

**Comment by Keats** [comment]
Yep we automatically create some _index.md at the root of the content if there isn't one just so you actually have a homepage.
