### ISSUE TITLE
Why is baseurl required not to be empty?

### ISSUE THREAD

**Issue by marie-bnl** [Keats/gutenberg#2109]
(sorry for deleting the issue template it just doesn't fit here)

I have a zola project that builds an HTML that is never going to be a website. Basically I'll just open the html file locally. In that case, why can't I just have this in my config?

```
baseurl = ""
```

Of course I can put something random in the baseurl variable and it works, but it doesn't make much sense.

**Comment by Keats** [comment]
Well this is a static site generation tool and most sites have a URL. Some do not but they are the tiny minority and feeds will not work without a valid url.

Semi-duplicate of https://github.com/getzola/zola/issues/2089 so closing.

**Comment by c-git** [comment]
@victorbnl 

I also use a site that I generate locally and for that I use the path on my machine so that links are still correct for example `file:///home/user/mysite/docs/`. Some themes (like [EasyDocs](https://www.getzola.org/themes/zola-easydocs-theme/) and [abridge](https://www.getzola.org/themes/abridge/)) also support links with the index.html on the end, which they call ugly urls, that will work instead of bringing you to the folder. Inter page links I still use the normal zola format because the verification that they are not broken is worth more to me than a relative link that would still work if I change to use a webserver.

PS. I use Firefox on linux not sure if it's different on other browsers or OS.

**Comment by marie-bnl** [comment]
Clever indeed, thank you.
