### ISSUE TITLE
section in content folder has layout options (template and page_template) in frontmatter

### ISSUE THREAD

**Issue by mevdschee** [Keats/gutenberg#2131]
# Feature request

I would expect that the content folder does not (have to) contain layout options, such as the "template" and "page_template" options in the template frontmatter and that the layout can be fully managed from the "templates" folder. I would suggest to solve it the way Hugo does: use a template search order. So, for the file "content/blog/_index.md" look for "templates/blog/list.html" first and if that does not exist look for "templates/list.html". You can still support the "template" and "page_template" frontmatter and therefor it does not break too many sites.

The separation between content and layout is very important to me and I would like zola to respect that. Thank you for reading and considering and please let me know if I overlooked some option.

**Comment by Keats** [comment]
That is not going to change.

> The separation between content and layout is very important to me and I would like zola to respect that

That's not really the case in Hugo since you need to reproduce the exact same file path as in the content directory. Move things in the content directory and you need to update the templates folder.

And personally I find having 20+ different possible locations for a template way more confusing to understand than having it defined explicitly with the rest of the section/page configuration. I just checked https://gohugo.io/templates/lookup-order/ and some examples have 37 possible templates. I'll happily let that feature in Hugo.

**Comment by mevdschee** [comment]
@Keats Thank you for swift reply and your excellent project. You make a very good point in your reply. Please keep it up!

Note for anyone else interested in this feature that I was also able to work around this by conditionally including different files in the two main templates. Maybe that works for you too. Enjoy!
